# Generated by Django 4.2.4 on 2023-09-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='', upload_to='course_image/% Y/% m/% d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.PositiveIntegerField(),
        ),
    ]
