# Generated by Django 4.2.4 on 2023-09-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_student_invited_by'),
        ('instructor', '0002_course_image_alter_course_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='StudentCourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_anytime', models.BooleanField(default=False)),
                ('specific_time_start', models.DateTimeField(blank=True, null=True)),
                ('specific_time_end', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='instructor.StudentCourseAccess', to='register.student'),
        ),
    ]
