# Generated by Django 4.2.4 on 2023-09-16 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourseaccess',
            name='can_view_anytime',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentcourseaccess',
            name='specific_time_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentcourseaccess',
            name='specific_time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
