# Generated by Django 4.2.4 on 2023-09-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_student_invited_by'),
        ('instructor', '0006_alter_studentcourseaccess_can_view_anytime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='studentcourseaccess',
            name='course',
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(through='instructor.StudentCourseAccess', to='register.student'),
        ),
        migrations.AddField(
            model_name='studentcourseaccess',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='instructor.lesson'),
            preserve_default=False,
        ),
    ]
