# Generated by Django 4.2.4 on 2023-09-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0009_quiz_question_choice_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='student_answer',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='instructor.choice'),
            preserve_default=False,
        ),
    ]
