# Generated by Django 4.2.4 on 2023-09-20 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_student_invited_by'),
        ('instructor', '0011_studentcourseaccess_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='student_complete',
            field=models.ManyToManyField(through='instructor.CompleteCourse', to='register.student'),
        ),
    ]
