# Generated by Django 4.2.4 on 2023-09-20 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0012_completecourse_course_student_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='student_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='instructor.choice'),
        ),
    ]
