# Generated by Django 4.2.4 on 2023-09-25 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0013_alter_answer_question_alter_answer_student_answer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='student and question'),
        ),
        migrations.AddConstraint(
            model_name='completecourse',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='student and course'),
        ),
    ]
