# Generated by Django 4.2.4 on 2023-09-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0014_answer_student_and_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='pdf',
            field=models.FileField(default='', upload_to='pdfs/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
