# Generated by Django 4.2.4 on 2023-09-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0015_section_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=100)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructor.section')),
            ],
        ),
    ]
