# Generated by Django 4.2.4 on 2023-09-26 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0016_livemeeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemeeting',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='livemeeting',
            name='roomid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
