# Generated by Django 4.2.4 on 2023-09-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0018_alter_section_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livemeeting',
            name='roomid',
        ),
        migrations.AddField(
            model_name='livemeeting',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
