# Generated by Django 4.2.4 on 2023-09-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='superuser',
            new_name='staffuser',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='superuser',
            new_name='staffuser',
        ),
    ]
