# Generated by Django 4.2.4 on 2023-09-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_student_invited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.instructor'),
        ),
    ]
