# Generated by Django 4.2.4 on 2023-09-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_student_invited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FileField(default='static/img/student.png', upload_to='student_photo/%Y/%m/%d/'),
        ),
    ]
