# Generated by Django 4.2.4 on 2023-09-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='student_photo/%Y/%m/%d/'),
        ),
    ]
