# Generated by Django 4.2.4 on 2023-09-28 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_invitation_expiration_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expiration_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
