# Generated by Django 4.2.4 on 2023-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='student_mark',
            field=models.IntegerField(),
        ),
    ]
