# Generated by Django 4.2.4 on 2023-09-28 01:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_replay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replay',
            new_name='Reply',
        ),
    ]
